# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
# Install APT package as explained in:
# https://docs.readthedocs.io/en/stable/build-customization.html
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - make
  jobs:
    # https://docs.readthedocs.io/en/stable/build-customization.html
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - poetry install --with docs
      - poetry build
      - pip install dist/*whl
    pre_build:
      # Generate autodoc and call sphinx
      - make docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
